# Generated by Django 2.0 on 2018-09-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='编写内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('node', models.CharField(choices=[('生物知识', '生物知识'), ('生物信息', '生物信息'), ('生活交流', '生活交流'), ('生信编程', '生信编程'), ('计算机学习', '计算机学习'), ('django学习', 'django学习')], max_length=50, verbose_name='主题结点')),
                ('top', models.CharField(max_length=5, verbose_name='是否置顶')),
                ('notice', models.CharField(max_length=5, verbose_name='公告')),
            ],
            options={
                'verbose_name': '发布主题',
                'verbose_name_plural': '发布主题',
            },
        ),
        migrations.CreateModel(
            name='Topic_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Create_Topic', verbose_name='关联主题')),
            ],
            options={
                'verbose_name': '用户对主题进行评论',
                'verbose_name_plural': '用户对主题进行评论',
            },
        ),
    ]
